/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationPrivateRouteImport } from './routes/validation-private'
import { Route as JoinBetaRouteImport } from './routes/join-beta'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogPhoneTheftAtAnAllTimeHighRouteImport } from './routes/blog/phone-theft-at-an-all-time-high'
import { Route as BlogIsYourDataTheftProofRouteImport } from './routes/blog/is-your-data-theft-proof'
import { Route as BlogHowToPreventPickpocketingRouteImport } from './routes/blog/how-to-prevent-pickpocketing'
import { Route as BlogHasYourPhoneBeenStolenRouteImport } from './routes/blog/has-your-phone-been-stolen'
import { Route as BlogAreYouAPickpocketTargetRouteImport } from './routes/blog/are-you-a-pickpocket-target'

const ValidationPrivateRoute = ValidationPrivateRouteImport.update({
  id: '/validation-private',
  path: '/validation-private',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinBetaRoute = JoinBetaRouteImport.update({
  id: '/join-beta',
  path: '/join-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPhoneTheftAtAnAllTimeHighRoute =
  BlogPhoneTheftAtAnAllTimeHighRouteImport.update({
    id: '/blog/phone-theft-at-an-all-time-high',
    path: '/blog/phone-theft-at-an-all-time-high',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIsYourDataTheftProofRoute =
  BlogIsYourDataTheftProofRouteImport.update({
    id: '/blog/is-your-data-theft-proof',
    path: '/blog/is-your-data-theft-proof',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToPreventPickpocketingRoute =
  BlogHowToPreventPickpocketingRouteImport.update({
    id: '/blog/how-to-prevent-pickpocketing',
    path: '/blog/how-to-prevent-pickpocketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHasYourPhoneBeenStolenRoute =
  BlogHasYourPhoneBeenStolenRouteImport.update({
    id: '/blog/has-your-phone-been-stolen',
    path: '/blog/has-your-phone-been-stolen',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAreYouAPickpocketTargetRoute =
  BlogAreYouAPickpocketTargetRouteImport.update({
    id: '/blog/are-you-a-pickpocket-target',
    path: '/blog/are-you-a-pickpocket-target',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/getting-started': typeof GettingStartedRoute
  '/join-beta': typeof JoinBetaRoute
  '/validation-private': typeof ValidationPrivateRoute
  '/blog/are-you-a-pickpocket-target': typeof BlogAreYouAPickpocketTargetRoute
  '/blog/has-your-phone-been-stolen': typeof BlogHasYourPhoneBeenStolenRoute
  '/blog/how-to-prevent-pickpocketing': typeof BlogHowToPreventPickpocketingRoute
  '/blog/is-your-data-theft-proof': typeof BlogIsYourDataTheftProofRoute
  '/blog/phone-theft-at-an-all-time-high': typeof BlogPhoneTheftAtAnAllTimeHighRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/getting-started': typeof GettingStartedRoute
  '/join-beta': typeof JoinBetaRoute
  '/validation-private': typeof ValidationPrivateRoute
  '/blog/are-you-a-pickpocket-target': typeof BlogAreYouAPickpocketTargetRoute
  '/blog/has-your-phone-been-stolen': typeof BlogHasYourPhoneBeenStolenRoute
  '/blog/how-to-prevent-pickpocketing': typeof BlogHowToPreventPickpocketingRoute
  '/blog/is-your-data-theft-proof': typeof BlogIsYourDataTheftProofRoute
  '/blog/phone-theft-at-an-all-time-high': typeof BlogPhoneTheftAtAnAllTimeHighRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/getting-started': typeof GettingStartedRoute
  '/join-beta': typeof JoinBetaRoute
  '/validation-private': typeof ValidationPrivateRoute
  '/blog/are-you-a-pickpocket-target': typeof BlogAreYouAPickpocketTargetRoute
  '/blog/has-your-phone-been-stolen': typeof BlogHasYourPhoneBeenStolenRoute
  '/blog/how-to-prevent-pickpocketing': typeof BlogHowToPreventPickpocketingRoute
  '/blog/is-your-data-theft-proof': typeof BlogIsYourDataTheftProofRoute
  '/blog/phone-theft-at-an-all-time-high': typeof BlogPhoneTheftAtAnAllTimeHighRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/getting-started'
    | '/join-beta'
    | '/validation-private'
    | '/blog/are-you-a-pickpocket-target'
    | '/blog/has-your-phone-been-stolen'
    | '/blog/how-to-prevent-pickpocketing'
    | '/blog/is-your-data-theft-proof'
    | '/blog/phone-theft-at-an-all-time-high'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/getting-started'
    | '/join-beta'
    | '/validation-private'
    | '/blog/are-you-a-pickpocket-target'
    | '/blog/has-your-phone-been-stolen'
    | '/blog/how-to-prevent-pickpocketing'
    | '/blog/is-your-data-theft-proof'
    | '/blog/phone-theft-at-an-all-time-high'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/getting-started'
    | '/join-beta'
    | '/validation-private'
    | '/blog/are-you-a-pickpocket-target'
    | '/blog/has-your-phone-been-stolen'
    | '/blog/how-to-prevent-pickpocketing'
    | '/blog/is-your-data-theft-proof'
    | '/blog/phone-theft-at-an-all-time-high'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GettingStartedRoute: typeof GettingStartedRoute
  JoinBetaRoute: typeof JoinBetaRoute
  ValidationPrivateRoute: typeof ValidationPrivateRoute
  BlogAreYouAPickpocketTargetRoute: typeof BlogAreYouAPickpocketTargetRoute
  BlogHasYourPhoneBeenStolenRoute: typeof BlogHasYourPhoneBeenStolenRoute
  BlogHowToPreventPickpocketingRoute: typeof BlogHowToPreventPickpocketingRoute
  BlogIsYourDataTheftProofRoute: typeof BlogIsYourDataTheftProofRoute
  BlogPhoneTheftAtAnAllTimeHighRoute: typeof BlogPhoneTheftAtAnAllTimeHighRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-private': {
      id: '/validation-private'
      path: '/validation-private'
      fullPath: '/validation-private'
      preLoaderRoute: typeof ValidationPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-beta': {
      id: '/join-beta'
      path: '/join-beta'
      fullPath: '/join-beta'
      preLoaderRoute: typeof JoinBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/phone-theft-at-an-all-time-high': {
      id: '/blog/phone-theft-at-an-all-time-high'
      path: '/blog/phone-theft-at-an-all-time-high'
      fullPath: '/blog/phone-theft-at-an-all-time-high'
      preLoaderRoute: typeof BlogPhoneTheftAtAnAllTimeHighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/is-your-data-theft-proof': {
      id: '/blog/is-your-data-theft-proof'
      path: '/blog/is-your-data-theft-proof'
      fullPath: '/blog/is-your-data-theft-proof'
      preLoaderRoute: typeof BlogIsYourDataTheftProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-prevent-pickpocketing': {
      id: '/blog/how-to-prevent-pickpocketing'
      path: '/blog/how-to-prevent-pickpocketing'
      fullPath: '/blog/how-to-prevent-pickpocketing'
      preLoaderRoute: typeof BlogHowToPreventPickpocketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/has-your-phone-been-stolen': {
      id: '/blog/has-your-phone-been-stolen'
      path: '/blog/has-your-phone-been-stolen'
      fullPath: '/blog/has-your-phone-been-stolen'
      preLoaderRoute: typeof BlogHasYourPhoneBeenStolenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/are-you-a-pickpocket-target': {
      id: '/blog/are-you-a-pickpocket-target'
      path: '/blog/are-you-a-pickpocket-target'
      fullPath: '/blog/are-you-a-pickpocket-target'
      preLoaderRoute: typeof BlogAreYouAPickpocketTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GettingStartedRoute: GettingStartedRoute,
  JoinBetaRoute: JoinBetaRoute,
  ValidationPrivateRoute: ValidationPrivateRoute,
  BlogAreYouAPickpocketTargetRoute: BlogAreYouAPickpocketTargetRoute,
  BlogHasYourPhoneBeenStolenRoute: BlogHasYourPhoneBeenStolenRoute,
  BlogHowToPreventPickpocketingRoute: BlogHowToPreventPickpocketingRoute,
  BlogIsYourDataTheftProofRoute: BlogIsYourDataTheftProofRoute,
  BlogPhoneTheftAtAnAllTimeHighRoute: BlogPhoneTheftAtAnAllTimeHighRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
